CREATE DATABASE USERTREE;
GO

USE USERTREE

CREATE TABLE TipoUsuario
(
	idTipoU TINYINT PRIMARY KEY IDENTITY (1,1),
	tipoU VARCHAR(30) UNIQUE NOT NULL
)
GO

CREATE TABLE Usuarios
(
	idUsuario TINYINT PRIMARY KEY IDENTITY (1,1),
	idTipoU TINYINT FOREIGN KEY REFERENCES TipoUsuario(idTipoU),
	nome VARCHAR(30) NOT NULL,
	senha VARCHAR(200) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	statusU BIT NOT NULL
)

GO